### ISSUE TITLE
Subscribe to Notification feature 

### ISSUE THREAD

**Issue by makramalla** [CESNET/Netopeer-GUI#107]
Hello,

I am having some issues maintaining a connection when trying to connect using Netopeer-GUI.
After a couple of minutes my session just stops and I am not able to get any response from the Client side.

I had a similar issue when I was working with Netopeer-CLI and the solution for that was to send a "subscribe" command that keeps my session connected.

Is there any similar approach that I could use on Netopeer-GUI, noting that preferably I would send this "subscribe" request as a first step before even parsing the modules to maintain the connection effectively.

Thank you for your continuous support, and let me know if you need any further clarification. 

Maged

**Comment by michalvasko** [comment]
Hi Maged,
sorry to disappoint you, but *netopeer-gui* is not really supported anymore as we have plans of replacing it with a new GUI and this one's development stopped. If session idle-timeouts are too small for you then increasing them in *netopeer-server* may be enough.

Regards,
Michal

**Comment by makramalla** [comment]
Hi Michal,

Thank you for your reply. I will try testing that.

Really looking forward for your new release.
Good luck!

Maged
