### ISSUE TITLE
Section data not displayed

### ISSUE THREAD

**Issue by davidkupka** [CESNET/Netopeer-GUI#26]
Steps to reproduce:
1. Log in to NetopeerGUI.
2. Connect to any netconf server.
3. Click 'Session info' icon.
4. Click 'Lock' or 'Unlock'.
5. Click any section.

Expected behavior:
Relevant section data will be displayed.

Current behavior:
Session info is displayed.

**Comment by alexadavid** [comment]
we are working on new version (developed in https://github.com/CESNET/Netopeer-GUI/tree/netopeerguid). This issue is not actual any more.
