### ISSUE TITLE
Buffering of create/delete operations

### ISSUE THREAD

**Issue by davidkupka** [CESNET/Netopeer-GUI#29]
Every create or delete operation is immediately sent to server and performed. Considering that every such change cause restart of some service or reconfiguration of HW component It will be useful to cache such operation and then send them all at once.

I suggest adding one extra button ('Add change to cache') next to 'Create new node' or 'Delete record'. The cached operation will then be confirmed using 'Save changes' button.

**Comment by alexadavid** [comment]
we are working on new version (developed in https://github.com/CESNET/Netopeer-GUI/tree/netopeerguid). This issue is not actual any more.
