### ISSUE TITLE
auto validate not send edit-config asynchronously 

### ISSUE THREAD

**Issue by alexadavid** [CESNET/Netopeer-GUI#36]
relaxNG? schama? or send validate command to server?

**Comment by cejkato2** [comment]
From mod_netconf:
NC_EDIT_TESTOPT_TYPE parse_testopt(const char *t)
{
        if (strcmp(t, "notset") == 0) {
                return NC_EDIT_TESTOPT_NOTSET;
        } else if (strcmp(t, "testset") == 0) {
                return NC_EDIT_TESTOPT_TESTSET;
        } else if (strcmp(t, "set") == 0) {
                return NC_EDIT_TESTOPT_SET;
        } else if (strcmp(t, "test") == 0) {
                return NC_EDIT_TESTOPT_TEST;
        }
        return NC_EDIT_TESTOPT_ERROR;
}

**Comment by alexadavid** [comment]
we are working on new version (developed in https://github.com/CESNET/Netopeer-GUI/tree/netopeerguid). This issue is not actual any more.
