### ISSUE TITLE
Bad description shown in Add child dialog

### ISSUE THREAD

**Issue by cejkato2** [CESNET/Netopeer-GUI#69]
Tried in Turing machine module:
add child for turing-machine, insert row transition function -> delta -> input
Input has 2 childen: state and symbol. Hint (description) for symbol is taken from description of symbol from output.

That means instead of "Symbol read from the tape cell." we can see "Symbol to be written to the tape cell. If this leaf is not present, the symbol doesn&apos;t change."

**Comment by alexadavid** [comment]
we are working on new version (developed in https://github.com/CESNET/Netopeer-GUI/tree/netopeerguid). This issue is not actual any more.
