### ISSUE TITLE
Appeal on install Netopeer-GUI

### ISSUE THREAD

**Issue by lilonghua2014** [CESNET/Netopeer-GUI#71]
I met a question,when I install Netopeer-GUI on ubuntu(12.04).As follow:
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/var/www/tmp/netopeer-gui/install/mod_netconf':
configure: error: C compiler cannot create executables
See `config.log' for more details
configure: error: ./configure failed for mod_netconf

config.log:
configure:4095: running /bin/bash ./configure --disable-option-checking '--prefix=/usr/local'  --cache-file=/dev/null --srcdir=.
configure:4100: error: ./configure failed for mod_netconf

mod_netconf config.log:
configure:4351: checking for C compiler version
configure:4360: gcc --version >&5
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:4371: $? = 0
configure:4360: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)
configure:4371: $? = 0
configure:4360: gcc -V >&5
gcc: error: unrecognized option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:4371: $? = 4
configure:4360: gcc -qversion >&5
gcc: error: unrecognized option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:4371: $? = 4
configure:4391: checking whether the C compiler works
configure:4413: gcc /usr/lib/x86_64-linux-gnu /usr/local/lib -I/usr/local/include   -I/usr/include/libxml2     conftest.c /usr/lib/x86_64-linux-gnu /usr/local/lib -L/usr/local/lib -lnetconf   -lxml2   >&5
/usr/bin/ld: cannot find /usr/lib/x86_64-linux-gnu: File format not recognized
/usr/bin/ld: cannot find /usr/local/lib: File format not recognized
/usr/bin/ld: cannot find /usr/lib/x86_64-linux-gnu: File format not recognized
/usr/bin/ld: cannot find /usr/local/lib: File format not recognized

collect2: ld returned 1 exit status
configure:4417: $? = 1
configure:4455: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "mod_netconf"
| #define PACKAGE_TARNAME "mod_netconf"
| #define PACKAGE_VERSION "1.0.0"
| #define PACKAGE_STRING "mod_netconf 1.0.0"
| #define PACKAGE_BUGREPORT "cejkat@cesnet.cz"
| #define PACKAGE_URL ""
| #define PACKAGE "mod_netconf"
| #define VERSION "1.0.0"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:4460: error: in `/var/www/tmp/netopeer-gui/install/mod_netconf':
configure:4462: error: C compiler cannot create executables
See `config.log' for more details

**Comment by Premilav** [comment]
I have installed "http://www.liberouter.org/docs/2014-11-24-netopeer-demo.ova". I could like to add few modules. Request you to let me know the steps to add new module to the above netconf-server.

**Comment by michalvasko** [comment]
Hi,

you can easily add your transAPI modules using *netopeer-manager*.

Regards,
Michal

**Comment by Premilav** [comment]
Hi Michal,

Thanks for the reply. I am using this "netopeergui", i am unable to execute any edit-config. Any help will be highly appreciated.

**Comment by alexadavid** [comment]
Hi, you can find basic informations in readme in virtual machine desktop.

...
Problems with NETCONF tools:
Try to look into log files:
        /var/log/messages (output from netopeer-server and netopeer-agent)
        /var/log/httpd/error_log (output from Netopeer-GUI backend)
        /var/www/netopeer-gui/app/logs/prod.*
...

But as I see now from discussion history, you have installed old demo version of virtual machine, please rather use one described here https://github.com/CESNET/Netopeer-GUI - it is last stable release of our demo.

**Comment by Premilav** [comment]
Hi, 

I am trying to do "edit-config" on the device, below is the RPC stack. Request you to let me know what is wrong in this. It throws the error "There is no device/data that could be affected".

<?xml version="1.0" encoding="UTF-8" standalone="no"?><hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><capabiliti
es><capability>urn:ietf:params:netconf:base:1.0</capability></capabilities></hello>
 The CONFIG TREE isiis : system

 The output isiis : clock
<?xml version="1.0" encoding="UTF-8" standalone="no"?><?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rpc message-id="1" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<lock><target><candidate/></target></lock>
</rpc><?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rpc message-id="2" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<edit-config>
<target><candidate/></target>
<test-option>set</test-option>
<config>
<system xmlns="xmlns=urn:ietf:params:xml:ns:yang:ietf-system">
<clock operation="create">
<timezone-name>PST</timezone-name>
</clock>
</system>
</config>
</edit-config>
</rpc>
REPLY:
 <?xml version="1.0" encoding="UTF-8" standalone="no"?><rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" messag
e-id="2">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message>There is no device/data that could be affected.</error-message>
  </rpc-error>
</rpc-reply>

**Comment by cejkato2** [comment]
It seems to me that NETCONF messages were badly pasted in here... try to enclose your "code" into:

\`\`\`
your XML samples
\`\`\`

and use "Preview" please...

**Comment by Premilav** [comment]
Thanks for the info.
I have added the module "toaster.yin" via "netopeergui-manager". The manager list shows the module is enabled.
<module name="toaster" xmlns="urn:ietf:params:xml:ns:yang:yin:1" 
<xmlns:toast="http://netconfcentral.org/ns/toaster">
<"yang-version value="1"">
<"namespace uri="http://netconfcentral.org/ns/toaster"">
<"prefix value="toast"">
<"organisation">
<"text">
Netconf Central
<"/text">
<"/organization">
This is the yin file i have added to "netopeergui" virtual box.Now when i do "get-config" with my own api it shows other default modules and not the module which i have added.

Please let me know what should i do, to get this data. Used netopeer-configurator, the UI says module is enabled.

**Comment by rkrejci** [comment]
Hi, did you upgraded the VM demo as suggested @alexadavid?

Can you provide the list of capabilities announced by the server? It is available in the GUI when you connect to a device and then on the "Configuration" screen there is Info icon on the left side of the upper bar (next to the lock icon). So just click on the icon and post the content.

**Comment by Premilav** [comment]
I have installed the latest one 
https://www.liberouter.org/docs/2015-05-11-netopeer-demo.ova as instructed. 

Now restarted the server in virtual box via UI-> popup->restart. NetopeerGui server is not getting initialized. Please let me know what might be the problem.
I am in need of Netconf server for testing all the netconf operations.

**Comment by Premilav** [comment]
While connect the server via netconf cli it says error : 
libnetconf error:Unable to connect to localhost:830
connect:connecting to the localhost:830 as user"(null)" failed.
Help is highly appreciated.

**Comment by rkrejci** [comment]
Does the `netopeer-server` provide some log messages? Try to start the server manually with a higher verbose level and check (post) the output:
```
# netopeer-server -v 3
```

**Comment by Premilav** [comment]
Thanks for response.
I removed few newly added modules via netopeer-manager. When i restarted the server, itis getting started is listed below, Now i would like to add one module and do get-config & edit-config. Any small sample module for testing. 
The server capabilities,
<?xml version="1.0" encoding="UTF-8" standalone="no"?><hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><capabiliti
es><capability>urn:ietf:params:netconf:base:1.0</capability></capabilities></hello>Session Established >>>>>>>>>>>>>>>>>
>>>>>>>>>>>>>>
CAPABILITIES :[urn:ietf:params:netconf:base:1.0, urn:ietf:params:netconf:base:1.1, urn:ietf:params:netconf:capability:writable-ru
nning:1.0, urn:ietf:params:netconf:capability:candidate:1.0, urn:ietf:params:netconf:capability:startup:1.0, urn:ietf:pa
rams:netconf:capability:rollback-on-error:1.0, urn:ietf:params:netconf:capability:interleave:1.0, urn:ietf:params:netcon
f:capability:notification:1.0, urn:ietf:params:netconf:capability:validate:1.0, urn:ietf:params:netconf:capability:valid
ate:1.1, urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&also-supported=report-all,report-all-t
agged,trim,explicit, urn:ietf:params:netconf:capability:url:1.0?scheme=scp,file, http://example.net/turing-machine?modul
e=turing-machine&revision=2013-12-27, urn:ietf:params:xml:ns:yang:ietf-system?module=ietf-system&revision=2014-08-06&fea
tures=authentication,local-users,timezone-name, urn:ietf:params:xml:ns:yang:ietf-ip?module=ietf-ip&revision=2014-06-16&f
eatures=ipv4-non-contiguous-netmasks,ipv6-privacy-autoconf, urn:ietf:params:xml:ns:yang:ietf-interfaces?module=ietf-inte
rfaces&revision=2014-05-08, urn:ietf:params:xml:ns:yang:iana-if-type?module=iana-if-type&revision=2014-05-08, urn:cesnet
:tmc:netopeer:1.0?module=netopeer-cfgnetopeer&revision=2015-01-15&features=ssh, urn:ietf:params:xml:ns:yang:ietf-netconf
-server?module=ietf-netconf-server&revision=2014-01-24&features=ssh,inbound-ssh,outbound-ssh, urn:ietf:params:xml:ns:yan
g:ietf-x509-cert-to-name?module=ietf-x509-cert-to-name&revision=2013-03-26, urn:ietf:params:xml:ns:yang:ietf-netconf-acm
?module=ietf-netconf-acm&revision=2012-02-22, urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults?module=ietf-netconf
-with-defaults&revision=2010-06-09, urn:ietf:params:xml:ns:netconf:notification:1.0?module=notifications&revision=2008-0
7-14, urn:ietf:params:xml:ns:netmod:notification?module=nc-notifications&revision=2008-07-14, urn:ietf:params:xml:ns:yan
g:ietf-netconf-notifications?module=ietf-netconf-notifications&revision=2011-08-07, urn:ietf:params:xml:ns:yang:ietf-net
conf-monitoring?module=ietf-netconf-monitoring&revision=2010-10-04, urn:ietf:params:xml:ns:netconf:base:1.0?module=ietf-
netconf&revision=2011-03-08&features=writable-running,candidate,rollback-on-error,validate,startup,url, urn:ietf:params:
xml:ns:yang:ietf-yang-types?module=ietf-yang-types&revision=2013-07-15, urn:ietf:params:xml:ns:yang:ietf-inet-types?modu
le=ietf-inet-types&revision=2010-09-24]
/&&&&&& Testing hasStartup() method bool value : true
/^^^^^^ Testing hasCandidate() method bool value : true
/****** Testing hasWritableRunning() bool value : true
/^^^^^^ Testing hasUrl() method bool value : false
/****** Testing hasXPath() method bool value : false
/^^^^^^ Testing hasInterleave() method bool value : true
/****** Testing hasPartialLock() method bool value : false
/^^^^^^ Testing hasRollbackOnError() method bool value : true
/****** Testing hasNotification() method bool value : true
/****** Testing hasConfirmedCommit() method bool value : false
/****** Testing hasValidate() method bool value : true
<?xml version="1.0" encoding="UTF-8" standalone="no"?><rpc message-id="1" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0

**Comment by Premilav** [comment]
Hi,

Could anyone tell me how the edit-config will be carried out for groups.

**Comment by alexadavid** [comment]
Hello,
what do you exactly mean carried out for groups? Do you mean groups in linux module (called system in demo)? Or <edit-config> for more devices (group of devices)?

**Comment by Premilav** [comment]
Hi,
"Grouping in Netconf" 
Eg : https://www.ietf.org/mail-archive/web/netconf/current/msg10318.html
Few yang files have a set of groups named as "Grouping"
http://dld.netconfcentral.org/src/ietf-ipfix-psamp@2012-09-05.yang
How this is handled in netopeerGui server.

**Comment by michalvasko** [comment]
Hi,

groupings are basically just a syntactic construct, they are not handled specially. They get placed wherever *uses* with the name of the grouping occurs in the model to create the final model that is afterwards used in *NetopeerGUI*. You can see how the final model looks using, for instance, *pyang -f tree path-to-the-model-file*.

Regards,
Michal

**Comment by Premilav** [comment]
Hi,
When i did "edit-config" to netopeer, it says "ok"  message.But the value is not added/modified in the server. What would be the problem.

**Comment by rkrejci** [comment]
The problem could be in your edit-config. It is impossible to say what should happen when we don't see the edit-config content and the content of the datastore being targeted. 

BTW, please note the name of this issue - "Appeal on install Netopeer-GUI" I guess that this has nothing to do with install process, so please open a new issue and be more specific in what you are doing, what is expected result and what is, in contrast, the real result.
