### ISSUE TITLE
Make install errors

### ISSUE THREAD

**Issue by calciajd** [CESNET/Netopeer-GUI#74]
After running ./configure, sudo make install results in compiler errors for notification-server.c shown below.

Making install in mod_netconf
make[1]: Entering directory `/var/www/netopeer-gui/install/mod_netconf'
Making install in src
make[2]: Entering directory `/var/www/netopeer-gui/install/mod_netconf/src'
gcc -lwebsockets -L/lib -ljson-c   -L/usr/local/lib -lwebsockets   -L/usr/local/lib -lnetconf   -lxml2   -I/usr/include/json-c   -I/usr/local/include   -I/usr/local/include   -I/usr/include/libxml2   -DWITH_NOTIFICATIONS -DHTTPD_INDEPENDENT  `apr-1-config  --cflags --cppflags --includes --link-ld` -I/usr/include/httpd  -laprutil-1 -o webgui-backend ./mod_netconf.c ./notification-server.c
./mod_netconf.c: In function ‘netconf_callback_error_process’:
./mod_netconf.c:232: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c: In function ‘prepare_status_message’:
./mod_netconf.c:264: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c: In function ‘handle_op_connect’:
./mod_netconf.c:1131: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1132: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1133: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1134: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1136: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c: In function ‘handle_op_get’:
./mod_netconf.c:1195: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c: In function ‘handle_op_getconfig’:
./mod_netconf.c:1218: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1220: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c: In function ‘handle_op_getschema’:
./mod_netconf.c:1247: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1248: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1249: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c: In function ‘handle_op_editconfig’:
./mod_netconf.c:1284: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1285: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1287: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1290: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1296: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1297: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c: In function ‘handle_op_copyconfig’:
./mod_netconf.c:1370: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1373: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1376: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1377: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1378: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c: In function ‘handle_op_generic’:
./mod_netconf.c:1426: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c: In function ‘handle_op_kill’:
./mod_netconf.c:1476: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c: In function ‘handle_op_ntfgethistory’:
./mod_netconf.c:1611: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1612: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1613: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c: In function ‘handle_op_validate’:
./mod_netconf.c:1715: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1716: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1717: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c: In function ‘thread_routine’:
./mod_netconf.c:1828: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1829: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1887: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c:1900: warning: ‘json_object_object_get’ is deprecated (declared at /usr/include/json/json_object.h:271)
./mod_netconf.c: In function ‘forked_proc’:
./mod_netconf.c:2234: warning: passing argument 1 of ‘nc_callback_ssh_host_authenticity_check’ from incompatible pointer type
/usr/local/include/libnetconf/callbacks_ssh.h:116: note: expected ‘int (*)(const char *, struct LIBSSH2_SESSION *)’ but argument is of type ‘int (*)(const char *, int,  const char *)’
./notification-server.c: In function ‘callback_http’:
./notification-server.c:192: error: too few arguments to function ‘libwebsockets_serve_http_file’
./notification-server.c:284: error: ‘LWS_CALLBACK_SET_MODE_POLL_FD’ undeclared (first use in this function)
./notification-server.c:284: error: (Each undeclared identifier is reported only once
./notification-server.c:284: error: for each function it appears in.)
./notification-server.c:288: error: ‘LWS_CALLBACK_CLEAR_MODE_POLL_FD’ undeclared (first use in this function)
make[2]: *** [webgui-backend] Error 1
make[2]: Leaving directory `/var/www/netopeer-gui/install/mod_netconf/src'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/var/www/netopeer-gui/install/mod_netconf'
make: *** [install-recursive] Error 1

**Comment by cejkato2** [comment]
Would you please provide me information about version of libnetconf, libwebsockets, json-c?

If you want to try Netopeer-GUI, you can also try VirtualBox VM http://www.liberouter.org/docs/2014-11-24-netopeer-demo.ova

**Comment by calciajd** [comment]
libnetconf 0.9.0
libwebsockets 1.3
and
Name        : json-c
Arch        : i686
Version     : 0.11
Release     : 11.el6

**Comment by alexadavid** [comment]
I've updated dependency in install/mod_netconf (which is git submodule) into current version. Try whole installation again (run "git submodule update --init --recursive" in netopeergui root folder before)

**Comment by calciajd** [comment]
I did the following:
rm -rf netopeer-gui/
git clone --recursive https://github.com/cesnet/netopeer-gui.git
sudo ./bootstrap.sh
sudo -E ./configure
sudo -E make install

Now the warnings are gone, but there is still an error regarding ‘libwebsockets_serve_http_file’ shown below:

Making install in mod_netconf
make[1]: Entering directory `/var/www/netopeer-gui/install/mod_netconf'
Making install in src
make[2]: Entering directory `/var/www/netopeer-gui/install/mod_netconf/src'
gcc -lwebsockets -L/lib -ljson-c   -L/usr/local/lib -lwebsockets   -L/usr/local/lib -lnetconf   -lxml2   -I/usr/include/json-c   -I/usr/local/include   -I/usr/local/include   -I/usr/include/libxml2   -DWITH_NOTIFICATIONS -DHTTPD_INDEPENDENT  `apr-1-config  --cflags --cppflags --includes --link-ld` -I/usr/include/httpd  -laprutil-1 -o webgui-backend ./mod_netconf.c ./notification-server.c
./notification-server.c: In function ‘callback_http’:
./notification-server.c:192: error: too few arguments to function ‘libwebsockets_serve_http_file’
make[2]: *** [webgui-backend] Error 1
make[2]: Leaving directory `/var/www/netopeer-gui/install/mod_netconf/src'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/var/www/netopeer-gui/install/mod_netconf'
make: *** [install-recursive] Error 1

**Comment by cejkato2** [comment]
Unfortunately, I guess versions of your and our libwebsockets differ... This https://github.com/warmcat/libwebsockets/blob/master/lib/server.c#L1042 shows we have right number of parameters (5)...
I've just commited and pushed bugfix of configure.ac of mod_netconf in order to disable notifications (libwebsockets) at all.
Could you please try to get into mod_netconf/:
<pre>cd install/mod_netconf</pre>
switch to master and update again:
<pre>git checkout master; git pull</pre>
Then execute this:
<pre>./bootstrap.sh&&./configure --without-notifications&&make</pre>

I hope this will lead to successful compilation of mod_netconf without notification feature.
Then <pre>make install</pre> will install it.

If it didn't work, could you please send the output again?

To get notifications working, you will need to get the right version of libwebsockets... Will .src.rpm archive help you? Or we can provide x86_64 rpm for scientific linux 6...

**Comment by calciajd** [comment]
That worked. Thank you!

Which version of libwebsockets do I need? I used the latest from https://libwebsockets.org/trac/libwebsockets.

**Comment by cejkato2** [comment]
I've revisited the compilation a bit... Please, try the latest revision of mod_netconf and libwebsockets from here https://github.com/cejkato2/libwebsockets
