### ISSUE TITLE
How can I install the 'libwebsockets' package?

### ISSUE THREAD

**Issue by wangh13** [CESNET/Netopeer-GUI#80]
Hi all,
   When I tried to configure the netopeer-gui by following the guide, a mistake appeared.
![image](https://cloud.githubusercontent.com/assets/10665886/7368762/0973e3e2-edde-11e4-8a3b-b3734c3a8d8a.png)
   I also tried to git the source code of libwebsockets, but I can't find the setup files.

Thanks,
wangh

**Comment by cejkato2** [comment]
Sorry for the delay... I've revisit the compilation of mod_netconf a bit and created https://github.com/CESNET/mod_netconf/commit/dc8f08d7ddd38505b0dde91a6b13eb7146a0da8f
I hope it will work for you.

I have tested the installation from generated RPMs as it is shown in commit message.
