### ISSUE TITLE
error on make install command

### ISSUE THREAD

**Issue by mundo9090** [CESNET/Netopeer-GUI#81]
Hello,

I was able to successfully install the netopeer application, and now I want to install the netopeer GUI. I have been following the instructions provided here (I had to install a number of dependencies in order to reach the point where I am at right now) but when I run 'make install', I get the following errors below (I also attached the outputs of ./bootstrap.sh and ./configure):

root@netopeer-netopeer-instance-47qkfwlcsaqy:/var/www/netopeer-gui# ls
app  bin  composer.json  composer.phar  install  LICENSE  README.md  screenshots  src  web
root@netopeer-netopeer-instance-47qkfwlcsaqy:/var/www/netopeer-gui# cd install/
root@netopeer-netopeer-instance-47qkfwlcsaqy:/var/www/netopeer-gui/install# ls
bootstrap.sh  configure.ac  Makefile.am  mod_netconf  netopeergui.conf.in  pyang
root@netopeer-netopeer-instance-47qkfwlcsaqy:/var/www/netopeer-gui/install# ./bootstrap.sh 
configure.ac:97: installing './compile'
configure.ac:97: installing './config.guess'
configure.ac:97: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am: installing './INSTALL'
src/Makefile.am: installing './depcomp'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
root@netopeer-netopeer-instance-47qkfwlcsaqy:/var/www/netopeer-gui/install# ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking for rpmbuild... no
checking for httpd... no
checking for apachectl... /usr/sbin/apachectl
checking for php... /usr/bin/php
checking for php module dom... yes
checking for php module json... yes
checking for php module xml... yes
checking for php module pdo... yes
checking for php module intl... yes
checking for php module sysvsem... yes
checking for pyang... yes
checking for python... /usr/bin/python
checking for rpmbuild... (cached) no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating netopeergui.conf
config.status: creating pyang/Makefile
=== configuring in mod_netconf (/var/www/netopeer-gui/install/mod_netconf)
configure: running /bin/bash ./configure --disable-option-checking '--prefix=/usr/local'  --cache-file=/dev/null --srcdir=.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for apxs2... /usr/bin/apxs2
checking for rpmbuild... no
checking for httpd... no
checking for apachectl... /usr/sbin/apachectl
checking for php5_module in apache... yes
checking for rpmbuild... (cached) no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for json... yes
checking for websockets... yes
checking for apr... yes
checking for aprutil... yes
checking for netconf... yes
checking for xml... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for libwebsocket_create_context in -lwebsockets... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for int64_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for getdelim... yes
checking for gettimeofday... yes
checking for memset... yes
checking for socket... yes
checking for strdup... yes
checking for strerror... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: creating mod_netconf.spec
config.status: creating conf.d/Makefile
config.status: creating src/Makefile
config.status: executing depfiles commands

------------------------------------------------------------------------
mod_netconf 1.0.2
------------------------------------------------------------------------

Configuration Options Summary:

Documentation..........: 

Compilation............: make (or gmake)
  asxs.................: 
  LIBS.................: -lwebsockets -ljson-c   -lwebsockets   -L/usr/local/lib -lnetconf   -lxml2  
  CFLAGS...............: -I/usr/include/json-c     -I/usr/local/include   -I/usr/include/libxml2   -DWITH_NOTIFICATIONS

Installation...........: make install (as root if needed, with 'su' or 'sudo')
  prefix...............: /usr/local
  python module dir....: 
  webgui dir...........: 
  webgui name..........: 
  httpdmoduledir.......: Apache default path
  httpdconfddir........: /etc/httpd/conf.d
Su user for process:...............: 
Su group for process:..............: 
Chown user for sock file:...............: 
Chown group for sock file:..............: 

------------------------------------------------------------------------
netopeergui 1.0.0
------------------------------------------------------------------------

Configuration Options Summary:

Documentation..........: 

Compilation............: make (or gmake)
  asxs.................: 
  LIBS.................: 
  CFLAGS...............: 

Components
  mod_netconf..........: yes
  pyang plugins........: yes

Installation...........: make install (as root if needed, with 'su' or 'sudo')
  prefix...............: /usr/local
  python module dir....: /usr/lib/python2.7/dist-packages/pyang/plugins
  webgui dir...........: /var/www
  webgui name..........: netopeer-gui
  httpdmoduledir.......: Apache default path
  httpdconfddir........: /etc/httpd/conf.d

root@netopeer-netopeer-instance-47qkfwlcsaqy:/var/www/netopeer-gui/install# make install
Making install in mod_netconf
make[1]: Entering directory `/var/www/netopeer-gui/install/mod_netconf'
Making install in src
make[2]: Entering directory `/var/www/netopeer-gui/install/mod_netconf/src'
gcc -lwebsockets -ljson-c   -lwebsockets   -L/usr/local/lib -lnetconf   -lxml2   -I/usr/include/json-c     -I/usr/local/include   -I/usr/include/libxml2   -DWITH_NOTIFICATIONS -DHTTPD_INDEPENDENT  `apr-1-config  --cflags --cppflags --includes --link-ld` -I/usr/include/httpd  -laprutil-1 -o webgui-backend ./mod_netconf.c ./notification-server.c
./mod_netconf.c:58:19: fatal error: unixd.h: No such file or directory
 #include <unixd.h>
                   ^
compilation terminated.
In file included from ./notification-server.c:34:0:
./notification_module.h:48:19: fatal error: httpd.h: No such file or directory
 #include <httpd.h>
                   ^
compilation terminated.
make[2]: *** [webgui-backend] Error 1
make[2]: Leaving directory `/var/www/netopeer-gui/install/mod_netconf/src'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/var/www/netopeer-gui/install/mod_netconf'
make: *** [install-recursive] Error 1

Please help me out here, just to point it out I installed this on Ubuntu 14.04 (and I believe that httpd is the centOS version of apache but not sure).

Thank you!

**Comment by petrstehlik** [comment]
Hi,
from your logs and the error message it appears that you don't have httpd installed (checking for httpd... no). Just install httpd and everything should be fine (`apt-get install httpd`).

**Comment by cejkato2** [comment]
In fact, on my Fedora it is httpd-devel package. I expect that on Ubuntu etc. it is apache2-dev.
httpd.h is a header file of Apache server.

**Comment by gracehllee** [comment]
I have the same problem in Ubuntu 14.04, 
I already installed apache2-dev , but it still not working.

**Comment by cejkato2** [comment]
Try to look up that file.
According to https://packages.debian.org/sid/amd64/apache2-dev/filelist, httpd.h should be in /usr/include/apache2
That means you can try to add -I/usr/include/apache2 into CPPFLAGS.
