### ISSUE TITLE
 Netopeer GUI - remote server

### ISSUE THREAD

**Issue by tbrito01** [CESNET/Netopeer-GUI#82]
Hi,

I installed the demo Netopeer GUI and on the log in page I don't see an option to connect to a server as it shows in the wiki page. Can someone help me out with that?

Thanks!

Tatiana

**Comment by alexadavid** [comment]
Hello,
You can enable possibility to connect to any device by changing the configuration described in README (in the Desktop) (pasted bellow)

8) Changing Netopeer-GUI from Single Instance Mode

Disabling single instance mode allows multiple users and connection to remote NETCONF servers.
  1) go to /var/www/netopeer-gui (as root)
  2) edit app/config/parameters.yml (set param netopeer_single_instance: false)
  3) rm -rf app/netopeerWebgui.db app/cache/prod/*
  4) php composer.phar install
Default local user for log-in is admin with pass as password. After successful login into
Netopeer-GUI, user can connect to any NETCONF host with port, username and password.

**Comment by tbrito01** [comment]
Hi David,

Thank you very much for the steps to connect with a remote server. However when I ran step 4, I get the following:

![capture](https://cloud.githubusercontent.com/assets/15365533/10819696/cbd7edb2-7e1f-11e5-979f-a1c98b167153.PNG)

**Comment by alexadavid** [comment]
Hello,
sqlite, which is used as DB, doesn't support alter table. run 'rm /var/www/netopeer-gui/app/netopeerWebGui.db' (described in step 7 in readme)
--
S přáním příjemného zbytku dne
David Alexa

tel:    773685283

**Comment by tbrito01** [comment]
Hi David,

Once I remove /var/www/netopeer-gui/app/netopeerWebGui.db, do I need to re-run php composer.phar install again?

**Comment by tbrito01** [comment]
I just did it and the database schema updated successfully. :)

**Comment by tbrito01** [comment]
However for some reason I can't bring the Netopeer-GUI to open anymore. :( Any idea?

**Comment by tbrito01** [comment]
David,
I was able to get the option "login using eduID".  When I clicked on this option at the Login screen, I get a  Oops! An Error Occurred. The server returned a "500 Internal Server Error".

**Comment by tbrito01** [comment]
There is an issue with your install. Please let us if you can correct it from your end.

**Comment by tbrito01** [comment]
David, 

It is reporting
![captureerror](https://cloud.githubusercontent.com/assets/15365533/10821446/e350511a-7e28-11e5-8c3b-c5f9cc9e6748.PNG)
 an uncaught php exception... file attached.

**Comment by tbrito01** [comment]
David,
I was able to remote login to our server.  :)  But need your help to load our yand modules into the tool. How can I accomplish that? If you could please provide me instructions, it would be greatly appreciated.
 Thanks!

**Comment by alexadavid** [comment]
You should use netopeer-manager (https://github.com/CESNET/netopeer). This netopeer library is already installed as a part of NetopeerGUI backend. With this utility, you can load your YANG modules for localhost.

**Comment by tbrito01** [comment]
Yes, I did use the netopeer-manager to upload our yang modules. Once I have
all in the server, I can do a get config or is there anything else I need
to do in order to get the modules to work with the GUI?

**Comment by alexadavid** [comment]
You should restart netopeer-server service (run 'service netopeer.rc restart')

**Comment by tbrito01** [comment]
Thanks David for answering my questions. I tried to restart netopeer-server
service, however it returns a failed and it says server is not running.  I
used netopeer-configurator to check the Intercommunication settings and it
shows a problem.  Intercommunication: module init failed. Netopeer DBus
Configuration file not found.  I tried to restart my dbus service via
command "service messagebus restart" (not sure if it is the right command)
to reload its configuration but it did not help.

What am I doing wrong?

Tatiana

**Comment by michalvasko** [comment]
Hi Tatiana,

please provide the content of */var/log/messages*, the last netopeer-server start attempt error (a few lines at the end of the file). Thanks.

Regards,
Michal

**Comment by tbrito01** [comment]
Hi Michal,

Thank you. Here are the logs. It seems to be complaining the same
information in the netopeer-configurator. Attached the file with the
netopeer-configurator.

Nov  2 14:24:07 netopeer-gui kernel: sh[2148]: segfault at 0 ip (null) sp
00007fff2bb285a8 error 14 in bash[400000+d4000]
Nov  2 14:27:38 netopeer-gui netopeer-server[2297]: Unable to monitor
"/etc/sysconfig/network-scripts/ifcfg-eth0" (No such file or directory)
Nov  2 14:27:38 netopeer-gui netopeer-server[2297]: Datastore file
/usr/local/etc/netopeer/modules.conf.d cannot be opened (Is a directory).
Nov  2 14:27:38 netopeer-gui netopeer-server[2297]: Callback for path
/A:netopeer/A:modules/A:module/A:enabled failed (1).
Nov  2 14:27:39 netopeer-gui netopeer-server[2297]:
callback_n_netopeer_n_modules_n_module_n_enabled: internal error: module to
disable not found
Nov  2 14:27:39 netopeer-gui netopeer-server[2297]: Failed perform initial
copy of startup to running.
Nov  2 14:27:39 netopeer-gui netopeer-server[2297]: Device initialization
of module Netopeer failed.
Nov  2 14:27:39 netopeer-gui netopeer-server[2297]: Starting necessary
Netopeer plugin failed!

**Comment by michalvasko** [comment]
Hi Tatiana,

this seems to be a configuration error. Without more information I cannot identify the specific module that has the path to its datastore wrong, but I suspect some of the ones you added. You need to change the path **/usr/local/etc/netopeer/modules.conf.d** in the module configuration to point to a file (existing or not, it will be created) where the datastore content will be stored. This should solve your problem.

Regards,
Michal

**Comment by tbrito01** [comment]
Hi Michal,

I add the modules using the command below:
netopeer-manager add  --name overture-common-types --model
/home/netopeergui/Documents/overture-common-types.yin --datastore
/usr/local/etc/netopeer/modules.conf.d
netopeer-manager add  --name overture-config --model
/home/netopeergui/Documents/overture-config.yin --datastore
/usr/local/etc/netopeer/modules.conf.d

I guess I am point to the wrong path for the datastore?  Do I need to
create a file and add tot he --datastore path? What does the path should be
/usr/local/etc/netopeer/filename?



More info from /var/log/messages

Nov  2 14:20:48 netopeer-gui rtkit-daemon[1994]: Sucessfully made thread
1992 of process 1992 (/usr/bin/pulseaudio) owned by '500' high priority at
nice level -11.
Nov  2 14:20:48 netopeer-gui pulseaudio[1992]: pid.c: Stale PID file,
overwriting.
Nov  2 14:24:03 netopeer-gui kernel: lo: Disabled Privacy Extensions
Nov  2 14:24:03 netopeer-gui kernel: lo: Disabled Privacy Extensions
Nov  2 14:24:07 netopeer-gui kernel: sh[2148]: segfault at 0 ip (null) sp
00007fff2bb285a8 error 14 in bash[400000+d4000]
Nov  2 14:27:38 netopeer-gui netopeer-server[2297]: Unable to monitor
"/etc/sysconfig/network-scripts/ifcfg-eth0" (No such file or directory)
Nov  2 14:27:38 netopeer-gui netopeer-server[2297]: Datastore file
/usr/local/etc/netopeer/modules.conf.d cannot be opened (Is a directory).
Nov  2 14:27:38 netopeer-gui netopeer-server[2297]: Callback for path
/A:netopeer/A:modules/A:module/A:enabled failed (1).
Nov  2 14:27:39 netopeer-gui netopeer-server[2297]:
callback_n_netopeer_n_modules_n_module_n_enabled: internal error: module to
disable not found
Nov  2 14:27:39 netopeer-gui netopeer-server[2297]: Failed perform initial
copy of startup to running.
Nov  2 14:27:39 netopeer-gui netopeer-server[2297]: Device initialization
of module Netopeer failed.
Nov  2 14:27:39 netopeer-gui netopeer-server[2297]: Starting necessary
Netopeer plugin failed!
Nov  2 14:47:51 netopeer-gui netopeer-server[2403]: Unable to monitor
"/etc/sysconfig/network-scripts/ifcfg-eth0" (No such file or directory)
Nov  2 14:47:52 netopeer-gui netopeer-server[2403]: Datastore file
/usr/local/etc/netopeer/modules.conf.d cannot be opened (Is a directory).
Nov  2 14:47:52 netopeer-gui netopeer-server[2403]: Callback for path
/A:netopeer/A:modules/A:module/A:enabled failed (1).
Nov  2 14:47:52 netopeer-gui netopeer-server[2403]:
callback_n_netopeer_n_modules_n_module_n_enabled: internal error: module to
disable not found
Nov  2 14:47:52 netopeer-gui netopeer-server[2403]: Failed perform initial
copy of startup to running.
Nov  2 14:47:52 netopeer-gui netopeer-server[2403]: Device initialization
of module Netopeer failed.
Nov  2 14:47:52 netopeer-gui netopeer-server[2403]: Starting necessary
Netopeer plugin failed!
Nov  2 14:48:07 netopeer-gui netopeer-server[2426]: Unable to monitor
"/etc/sysconfig/network-scripts/ifcfg-eth0" (No such file or directory)
Nov  2 14:48:07 netopeer-gui netopeer-server[2426]: Datastore file
/usr/local/etc/netopeer/modules.conf.d cannot be opened (Is a directory).
Nov  2 14:48:07 netopeer-gui netopeer-server[2426]: Callback for path
/A:netopeer/A:modules/A:module/A:enabled failed (1).
Nov  2 14:48:07 netopeer-gui netopeer-server[2426]:
callback_n_netopeer_n_modules_n_module_n_enabled: internal error: module to
disable not found
Nov  2 14:48:07 netopeer-gui netopeer-server[2426]: Failed perform initial
copy of startup to running.
Nov  2 14:48:07 netopeer-gui netopeer-server[2426]: Device initialization
of module Netopeer failed.
Nov  2 14:48:07 netopeer-gui netopeer-server[2426]: Starting necessary
Netopeer plugin failed!
Nov  2 14:55:27 netopeer-gui netopeer-server[2470]: Failed to start, must
have root privileges.
[root@netopeer-gui log]#

**Comment by tbrito01** [comment]
Hi Michal,

Here are the logs from the netopeer-server:

[root@netopeer-gui log]# netopeer-server -v 5
netopeer-server[2513]: Shared memory key: -4
netopeer-server[2513]: Shared memory ID: 32769
netopeer-server[2513]: ncds_features_parse: no feature definitions found in
data model ietf-inet-types.
netopeer-server[2513]: ncds_features_parse: no feature definitions found in
data model ietf-yang-types.
netopeer-server[2513]: ncds_features_parse: no feature definitions found in
data model ietf-netconf-monitoring.
netopeer-server[2513]: ncds_features_parse: no feature definitions found in
data model ietf-netconf-notifications.
netopeer-server[2513]: ncds_features_parse: no feature definitions found in
data model nc-notifications.
netopeer-server[2513]: ncds_features_parse: no feature definitions found in
data model notifications.
netopeer-server[2513]: ncds_features_parse: no feature definitions found in
data model ietf-netconf-with-defaults.
netopeer-server[2513]: ncds_features_parse: no feature definitions found in
data model ietf-netconf-acm.
netopeer-server[2513]: ncds_set_validation: Relax NG validator set
(//var/lib/libnetconf//ietf-netconf-acm-config.rng)
netopeer-server[2513]: ncds_set_validation: Schematron validator set
(//var/lib/libnetconf//ietf-netconf-acm-schematron.xsl)
netopeer-server[2513]: Datastore ietf-netconf-acm initiated with ID 8.
netopeer-server[2513]: Checking the default Events stream path
//var/lib/libnetconf//streams/.
netopeer-server[2513]: Adding augment model
"/usr/local/etc/netopeer/cfgnetopeer/ietf-x509-cert-to-name.yin"
netopeer-server[2513]: ncds_features_parse: no feature definitions found in
data model ietf-x509-cert-to-name.
netopeer-server[2513]: Adding static transapi
"/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server.yin"
netopeer-server[2513]: ncds_new_internal: Relax NG validator set
(/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server-config.rng)
netopeer-server[2513]: ncds_new_internal: Schematron validator set
(/usr/local/etc/netopeer/cfgnetopeer/ietf-netconf-server-schematron.xsl)
netopeer-server[2513]: Datastore ietf-netconf-server initiated with ID
235979223.
netopeer-server[2513]: Setting the default SSH configuration for the
ietf-netconf-server module...
netopeer-server[2513]: callback_srv_netconf_srv_listen_srv_port: SSH
listening on the port 830
netopeer-server[2513]: Adding static transapi
"/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer.yin"
netopeer-server[2513]: ncds_new_internal: Relax NG validator set
(/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer-config.rng)
netopeer-server[2513]: ncds_new_internal: Schematron validator set
(/usr/local/etc/netopeer/cfgnetopeer/netopeer-cfgnetopeer-schematron.xsl)
netopeer-server[2513]: Datastore netopeer-cfgnetopeer initiated with ID
915336209.
netopeer-server[2513]: Setting the default configuration for the
cfgnetopeer module...
netopeer-server[2513]: Setting the default configuration for the
cfgnetopeer module SSH...
netopeer-server[2513]: Transapi calling callback
/A:netopeer/A:modules/A:module/A:enabled with op ADD.
netopeer-server[2513]: Adding augment model
"/usr/local/etc/netopeer/ietf-interfaces/iana-if-type.yin"
netopeer-server[2513]: ncds_features_parse: no feature definitions found in
data model iana-if-type.
netopeer-server[2513]: Adding transapi
"/usr/local/etc/netopeer/ietf-interfaces/ietf-interfaces.yin"
netopeer-server[2513]: ncds_new_internal: Relax NG validator set
(/usr/local/etc/netopeer/ietf-interfaces/ietf-interfaces-config.rng)
netopeer-server[2513]: ncds_new_internal: Schematron validator set
(/usr/local/etc/netopeer/ietf-interfaces/ietf-interfaces-schematron.xsl)
netopeer-server[2513]: Adding augment model
"/usr/local/etc/netopeer/ietf-interfaces/ietf-ip.yin"
netopeer-server[2513]: Datastore ietf-interfaces initiated with ID
911389485.
netopeer-server[2513]: Model "ietf-interfaces" transAPI: nothing changed.
netopeer-server[2513]: Starting FMON thread for ietf-interfaces data model.
netopeer-server[2513]: Transapi calling callback
/A:netopeer/A:modules/A:module/A:enabled with op ADD.
netopeer-server[2513]: Adding transapi
"/usr/local/etc/netopeer/ietf-system/ietf-system.yin"
netopeer-server[2513]: ncds_new_internal: Relax NG validator set
(/usr/local/etc/netopeer/ietf-system/ietf-system-config.rng)
netopeer-server[2513]: Unable to monitor
"/etc/sysconfig/network-scripts/ifcfg-eth0" (No such file or directory)
netopeer-server[2513]: ncds_new_internal: Schematron validator set
(/usr/local/etc/netopeer/ietf-system/ietf-system-schematron.xsl)
netopeer-server[2513]: Datastore ietf-system initiated with ID 906483083.
netopeer-server[2513]: Model "ietf-system" transAPI: nothing changed.
netopeer-server[2513]: Starting FMON thread for ietf-system data model.
netopeer-server[2513]: Transapi calling callback
/A:netopeer/A:modules/A:module/A:enabled with op ADD.
netopeer-server[2513]: Adding transapi
"/usr/local/etc/netopeer/turing-machine/turing-machine.yin"
netopeer-server[2513]: ncds_features_parse: no feature definitions found in
data model turing-machine.
netopeer-server[2513]: ncds_new_internal: Relax NG validator set
(/usr/local/etc/netopeer/turing-machine/turing-machine-config.rng)
netopeer-server[2513]: ncds_new_internal: Schematron validator set
(/usr/local/etc/netopeer/turing-machine/turing-machine-schematron.xsl)
netopeer-server[2513]: Datastore turing-machine initiated with ID
1578823042.
netopeer-server[2513]: Model "turing-machine" transAPI: there was not a
single callback found for the configuration change.
netopeer-server[2513]: Transapi calling callback
/A:netopeer/A:modules/A:module/A:enabled with op ADD.
netopeer-server[2513]: Adding base model
"/home/netopeergui/Documents/iana-if-type.yin"
netopeer-server[2513]: ncds_features_parse: no feature definitions found in
data model iana-if-type.
netopeer-server[2513]: Module to enlink "iana-if-type" already exists.
netopeer-server[2513]: Missing RelaxNG schema for validation
(/home/netopeergui/Documents/iana-if-type-config.rng - No such file or
directory).
netopeer-server[2513]: Missing Schematron stylesheet for validation
(/home/netopeergui/Documents/iana-if-type-schematron.xsl - No such file or
directory).
netopeer-server[2513]: Datastore file
/usr/local/etc/netopeer/modules.conf.d cannot be opened (Is a directory).
netopeer-server[2513]: Unable to set path to datastore of the
'iana-if-type' transAPI module.
netopeer-server[2513]: Callback for path
/A:netopeer/A:modules/A:module/A:enabled failed (1).
netopeer-server[2513]: Transapi calling callback
/A:netopeer/A:modules/A:module/A:enabled with op REM.
netopeer-server[2513]: Stopping FMON thread.
netopeer-server[2513]: Transapi calling callback
/A:netopeer/A:modules/A:module/A:enabled with op REM.
netopeer-server[2513]: Stopping FMON thread.
netopeer-server[2513]: Transapi calling callback
/A:netopeer/A:modules/A:module/A:enabled with op REM.
netopeer-server[2513]: Transapi calling callback
/A:netopeer/A:modules/A:module/A:enabled with op REM.
netopeer-server[2513]: callback_n_netopeer_n_modules_n_module_n_enabled:
internal error: module to disable not found
netopeer-server[2513]: Reverting configuration changes via transAPI failed,
configuration may be inconsistent.
netopeer-server[2513]: Updating XML tree after TransAPI callbacks
netopeer-server[2513]: Failed perform initial copy of startup to running.
netopeer-server[2513]: Device initialization of module Netopeer failed.
netopeer-server[2513]: Netopeer SSH cleanup.
netopeer-server[2513]: Netopeer cleanup.
netopeer-server[2513]: Starting necessary Netopeer plugin failed!
netopeer-server[2513]: NETCONF Call Home cleanup.
[root@netopeer-gui log]#

**Comment by michalvasko** [comment]
Hi Tatiana,

yes, the path you specified there is wrong. If you look at the configuration of our modules (in that directory **/usr/local/etc/netopeer/modules.conf.d**), we create a directory for every transAPI module that includes all the models it uses plus the datastore file. You can do the same or organize it any other way, *netopeer-manager* argument *datastore* must point to a file, which will be created if it does not exist.

Nevertheless, you do not seem to understand our transAPI module concept, so I will try to briefly explain, but please also look at our [transAPI tutorial](https://rawgit.com/CESNET/libnetconf/master/doc/doxygen/html/d9/d25/transapi.html). Based on the log messages I believe you tried to add a transAPI module that has the main model *iana-if-type*. This is actually wrong, because that model does not have any configuration or state data, only identity definitions. So, you start with the main model you want to implement. That is the *model* argument. This model should have some actual data definitions (or at least some custom RPCs). The data themselves will be stored in the datastore file (which you got wrong). If this main model uses any other supplementary models (imports to or augments of the main model), use the corresponding *netopeer-manager* arguments. Note that you cannot combine these arguments (add more than one model), add all the models one-by-one in separate *netopeer-manager* calls.

Regards,
Michal

**Comment by tbrito01** [comment]
Hi Michal,

I think we might have gotten a bit confused here. I don't want to mess with
your server. I have the Netopeer GUI pointing to our Overture device with
our own daemon and wanted to upload our modules as I did and do a get
config from the GUI. I don't want use your server at all. I don't think I
need to do anything with the transAPIs.

I see in the GUI the options for Overture Interfaces but when I do get
Overture Conf it finds nothing.

pics attached

Thanks!

**Comment by tbrito01** [comment]
Hi Michal,

I was able to get conf successfully via GUI. But I can't edit anything.
From the GUI tutorial it seems I am missing NACM and once I ran
netopeer-configurator it shows a module init failure so I followed the
instructions from here:

NACM: Module init failed when running netopeer-configurator


Usually this means you need to update PKG_CONFIG_PATH.

export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig for root before invoking
this command.)

in root user's .bashrc file: export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

http://seguesoft.com/how-to-set-up-netopeer-server-to-use-with-netconfc#moduleint

It did not help. Any ideas?

By the way, thank you for taking time to answer our questions. We really
appreciate it.

Tatiana

**Comment by michalvasko** [comment]
Hi Tatiana,

then there is definitely some confusion. The Virtual Box image we provide as a NetopeerGUI demo consists of two main parts. There is the client part, *NetopeerGUI* (web browser graphical interface) and *mod_netconf* (back-end of NetopeerGUI that actually acts as a NETCONF client). Then there is the server part, which is mainly *netopeer-server* (full NETCONF server) with some additional small scripts namely *netopeer-configurator* (for simple adjustment of some basic netopeer-server options) and *netopeer-manager* (for managing netopeer-server transAPI modules). *netopeer-cli* (a NETCONF client with a command-line interface) is also included for testing and troubleshooting, it is not required for NetopeerGUI to work. Also, there is *libnetconf*, which is the main library netopeer-server and mod_netconf use and which implements NETCONF communication itself, but you should not need to worry about it.

By default, NetopeerGUI connects to the locally running netopeer-server, which is the demo use-case. So, you either do not connect to netopeer-server and have your own NETCONF server implementation, in which case it is useless to use any applications from the server part (such as netopeer-manager or netopeer-configurator). Or you can use netopeer-server, which was our intention. If you do, you do not have to worry about the NETCONF protocol at all, it is fully implemented for you to use. Moreover, transAPI was designed so that managing any actual devices using netopeer-server is as simple as possible, which is what you very likely want to do, more about it in the tutorial in my previous post.

Also, you can try to look on the Internet for some help, but it may not help you at all, the information is likely dated.

Regards,
Michal

**Comment by tbrito01** [comment]
Hi Michal,

Thank you for the detailed explanation of the components. Indeed my first
initial desire was to install netopeer-server, client. But then I was
advised to try the Netopeer GUI in the VM and add our modules to the tool.
I then disabled the single instance mode so I could connect remotely to our
NETCONF server. I used the step 8 from the Readme file and logged to the
GUI as admin and pass password. Entered our host IP address and the
credentials.Then I was guided to use netopeer-manager to add our modules.
That is where I sent an email and you mentioned that I was pointing to the
wrong path.

Therefore, my questions are as follows:

1. Do I use netopeer-manager to load our yang modules to the GUI or
mod_netconf? I reformtted them to extension .yin and used the command
netopeer-manager add --name -- module -- datastore

2. In the GUI, Configure device I have options to see Interfaces,
Interfaces state, Netconf state, Overture config, Overture slots and all.
Overture Config (Conf & State data) shows no results found(??)  attached
pic1. It only return results if I select from Overture conf drop down menu
option "all", results are for config & state data/ Config data only (pic
2).  The "+" is to create empty module. It appears that <get-config> and
<get> work.

3. Issue:  Don't have a way to save config. I would like use
<edit-config>.  In this link:  https://github.com/CESNET/Netopeer-GUI/wiki
 I see the slides and there is an option "save config".

Thank you!

**Comment by michalvasko** [comment]
Hi Tatiana,

like I said, using netopeer-manager adds modules to the local netopeer-server, it does not affect NetopeerGUi directly and in your case not at all.

1. No, NetopeerGUI manages models it receives in the hello message from your NETCONF server.

2. You did something wrong when attaching screenshots, please try again and use preview to make sure you have it right.

3. We will need more details. What exactly is the problem, the button is simply missing?

Regards,
Michal

**Comment by tbrito01** [comment]
Hi Michal,

1. Understood. I won't use netopeer-manager

2. Nothing was wrong it is a PNG file. I am attaching one file now. It
shows the lock config was successful. I changed the name description under
Interface to 7.1-A, but there is no button to save the config in the GUI.
Am I missing something?

Thanks!

**Comment by michalvasko** [comment]
Hi Tatiana,

it seems that any attachments are discarded. Please either upload the image to some hosting server (imageshack.com for example) and post link here or reply using github web interface where you can embed images directly ([guide](https://guides.github.com/features/mastering-markdown/)). We will not be able to help you otherwise.

Regards,
Michal

**Comment by tbrito01** [comment]
Hi Michal,

Here is the attachment. 
![capture_editconfig](https://cloud.githubusercontent.com/assets/15365533/10969848/d553d44a-8398-11e5-95d2-1366e6108358.PNG)
 I changed the name description under
Interface to 7.1-A, but there is no button to save the config in the GUI.
Am I missing something

**Comment by tbrito01** [comment]
Hit the comment button too fast. Prior of making the change, I changed the datastore to "Candidate" and lock the database.

**Comment by alexadavid** [comment]
Hello, the save button label was renamed to "commit all changes". You can find it behind whole configuration tree. 

![screen shot 2015-11-05 at 14 50 45](https://cloud.githubusercontent.com/assets/984450/10970115/c8ec1f3a-83cc-11e5-99a7-ca95b83393d2.png)

**Comment by tbrito01** [comment]
Hi David,

Just tried that and there is no commit all changes button. I am not using the demo but my own modules and remotely logged in to our own server.

Attachments below:

![edit_conf1](https://cloud.githubusercontent.com/assets/15365533/10971484/812f1668-83a2-11e5-92a8-5c2b740eff11.PNG)

![edit-conf2](https://cloud.githubusercontent.com/assets/15365533/10971491/8548924c-83a2-11e5-9543-5e21a10b7bc2.PNG)

**Comment by tbrito01** [comment]
Hi David,

Once I locked the datastore I selected the option "Interface State" similar to the screenshot info you sent me earlier and got the following error:

![capture](https://cloud.githubusercontent.com/assets/15365533/11006482/fbac035c-8491-11e5-90e2-adab2e871935.PNG)

Could you please let me know why we are getting this error as we move across the bar options while the datastore is locked?

Thanks,

Tatiana

**Comment by tbrito01** [comment]
Hi Michal,

We checked every single tab in the GUI and there is no button "Commit all changes".  Please help!  

FYI: The datastore is locked and we wanted to modify a parameter via edit config

**Comment by tbrito01** [comment]
Here is the proof that the "commit all changes" button can't be found anywhere in the tool.
![capture](https://cloud.githubusercontent.com/assets/15365533/11007744/1174ed04-849a-11e5-8093-127a7232cc2b.PNG)

**Comment by alexadavid** [comment]
we are working on new version (developed in https://github.com/CESNET/Netopeer-GUI/tree/netopeerguid). This issue is not actual any more.
