### ISSUE TITLE
EditConfig not updated in datastore

### ISSUE THREAD

**Issue by Premilav** [CESNET/Netopeer-GUI#83]
In NetopeerGUI, When i tried to do the edit-config for candidate datastore as given below,
<"system xmlns="urn:ietf:params:xml:ns:yang:ietf-system""> 
  <"clock"> 
    <"timezone-name>PST</timezone-name"> 
  <"/clock"> 
<"/system">
The output rpcreply is "ok". But the changes are not reflected in the datastore. I checked the datastore using the "get-config" command for the candidate datastore. Previously the edit-config was working, but after reboot of the server this problem araises.
Any help will be much appreciated.

**Comment by michalvasko** [comment]
Hi,
please embed the edit-config [as a code](https://guides.github.com/features/mastering-markdown/), what you posted is wrong. Thank you.

Regards,
Michal
