### ISSUE TITLE
fix commit all button

### ISSUE THREAD

**Issue by alexadavid** [CESNET/Netopeer-GUI#85]
show button correctly based on capabilities

rename this button to apply changes

move it somewhere up

**Comment by tbrito01** [comment]
Hi David,

Where can I pick up this fix if I am using the Netopeer GUI via remote server?

Thanks,

Tatiana

**Comment by alexadavid** [comment]
Hello, I'll implement this fix this week. This fix will be independent on local or remote server, it's just presentation layer. I'll send you basic instruction after.

**Comment by tbrito01** [comment]
Ok, great. Thank you so much David.

**Comment by tbrito01** [comment]
Can you send me the instructions to use this fix?

Thanks

Tatiana

**Comment by alexadavid** [comment]
yes - I'm writing a new email right now :)

**Comment by alexadavid** [comment]
1) cd /var/www/netopeer-gui/
2) git pull origin master
3) rm /var/www/netopeer-gui/app/netopeerWebGui.db
4) composer install

**Comment by tbrito01** [comment]
Hi David,

I get the following error on step 2:

[root@netopeer-gui Desktop]# cd /var/www/netopeer-gui/
[root@netopeer-gui netopeer-gui]# git pull origin master
error: Couldn't resolve host 'github.com' while accessing
https://github.com/cesnet/netopeer-gui/info/refs

fatal: HTTP request failed
[root@netopeer-gui netopeer-gui]#

Tatiana

**Comment by alexadavid** [comment]
ok, you should propably change remote url from ssh to https

git remote set-url origin https://github.com/CESNET/Netopeer-GUI.git

**Comment by tbrito01** [comment]
Step 2 now works, but it fails on step 4: Is the command "composer install"
missing something. It says command not found.

**Comment by alexadavid** [comment]
Oh, sorry, I didn't realize that there is probably no composer installed globally. If there is composer.phar file, you can run the command as php composer.phar install. Otherwise, if no composer.phar in netopeer-gui directory exists, you can download it from https://getcomposer.org. I'm sorry, I can't look into virtual machine right now, so that's the reason why I wrote these two options.

**Comment by tbrito01** [comment]
Hi David,

Thanks for answering me. I did the following: I did earlier php
composer.phar install and it did not pick up any changes. Then I tried php
composer.* install and it printed a code but I think it not right. I could
not log into the GUI anymore as admin and passpord as pass.

Let me know what could possibly go wrong.

Thanks!

**Comment by tbrito01** [comment]
David,

Here is the print out when I executed the command: php composer.phar
install.  Does it look right to you? There are two warnings while running
the composer install below:


[netopeergui@netopeer-gui Desktop]$ su root
Password:
[root@netopeer-gui Desktop]# cd /var/www/netopeer-gui/
[root@netopeer-gui netopeer-gui]# git remote set-url origin
https://github.com/CESNET/Netopeer-GUI.git
[root@netopeer-gui netopeer-gui]# rm
/var/www/netopeer-gui/app/netopeerWebGui.db
rm: remove regular empty file
`/var/www/netopeer-gui/app/netopeerWebGui.db'? yes
[root@netopeer-gui netopeer-gui]#
[root@netopeer-gui netopeer-gui]#
[root@netopeer-gui netopeer-gui]# php composer.phar install
Warning: This development build of composer is over 30 days old. It is
recommended to update it by running "composer.phar self-update" to get the
latest version.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in
composer.json. You may be getting outdated dependencies. Run update to
update them.
Nothing to install or update
Generating autoload files
Updating the "app/config/parameters.yml" file
Clearing the cache for the dev environment with debug true
Installing assets using the symlink option
Installing assets for Symfony\Bundle\FrameworkBundle into
web/bundles/framework
Installing assets for FIT\NetopeerBundle into web/bundles/fitnetopeer
Installing assets for FIT\Bundle\ModuleDefaultBundle into
web/bundles/fitmoduledefault
Installing assets for FIT\Bundle\ModuleXmlBundle into
web/bundles/fitmodulexml
Installing assets for Sensio\Bundle\DistributionBundle into
web/bundles/sensiodistribution
Created database for connection named
/var/www/netopeer-gui/app/netopeerWebGui.db
Generating entities for namespace "FIT"
  > backing up User.php to User.php~
  > generating FIT\NetopeerBundle\Entity\User
  > backing up BaseConnection.php to BaseConnection.php~
  > generating FIT\NetopeerBundle\Entity\BaseConnection
  > backing up UserCustomData.php to UserCustomData.php~
  > generating FIT\NetopeerBundle\Entity\UserCustomData
  > backing up ModuleController.php to ModuleController.php~
  > generating FIT\NetopeerBundle\Entity\ModuleController
  > backing up SamlUser.php to SamlUser.php~
  > generating FIT\NetopeerBundle\Entity\SamlUser
Updating database schema...
Database schema updated successfully! "9" queries were executed
Dumping all prod assets.
Debug mode is off.

21:23:32 [file+] /var/www/netopeer-gui/app/../web/css/stylesheet.css
21:23:32 [file+] /var/www/netopeer-gui/app/../web/js/compiled/default.js
21:23:32 [file+]
/var/www/netopeer-gui/app/../web/js/compiled/module-default.js
21:23:32 [file+] /var/www/netopeer-gui/app/../web/css/module-default.css
21:23:32 [file+] /var/www/netopeer-gui/app/../web/js/compiled/module-xml.js
21:23:32 [file+] /var/www/netopeer-gui/app/../web/css/module-xml.css

========================
Executing post install script.
========================
========================
End of post install script
========================
[root@netopeer-gui netopeer-gui]#

**Comment by tbrito01** [comment]
Hi David,

Did you have a chance to look the steps of my commands in the previous email and the output of the composer install? We would like to try your fix asap and if you please could provide us response it would be great.

Thank you,

Tatiana
