### ISSUE TITLE
Identify config data

### ISSUE THREAD

**Issue by Premilav** [CESNET/Netopeer-GUI#86]
In netopeerGui server, can anyone point out how to identify the "config" data in the netopeerGUI server.

**Comment by cejkato2** [comment]
Well NetopeerGUI *client* uses configuration data model in YIN.
Internally, the data model is processed by special plugin for pyang, however, this is the source of information for decision whether a piece of data is config or state.

Data models are received by get-schema operation of the NETCONF protocol.

Does your NETCONF server support get-schema?

**Comment by alexadavid** [comment]
we are working on new version (developed in https://github.com/CESNET/Netopeer-GUI/tree/netopeerguid). This issue is not actual any more.
