### ISSUE TITLE
netopeer-gui make install error

### ISSUE THREAD

**Issue by gracehllee** [CESNET/Netopeer-GUI#88]
I install netopeer-gui in Ubuntu14.04

after run the command "make install", it shows error message as below:
------------------------------------------------------------------------
root@netconf:/var/www/netopeer-gui/install# make install
Making install in mod_netconf
make[1]: Entering directory `/var/www/netopeer-gui/install/mod_netconf'
Making install in src
make[2]: Entering directory `/var/www/netopeer-gui/install/mod_netconf/src'
gcc -lwebsockets -ljson-c   -lwebsockets   -L/usr/local/lib -lnetconf   -lxml2   -I/usr/include/json-c     -I/usr/local/include   -I/usr/include/libxml2   -DWITH_NOTIFICATIONS -DHTTPD_INDEPENDENT  `apr-1-config  --cflags --cppflags --includes --link-ld` -I/usr/include/httpd  -laprutil-1 -o webgui-backend ./mod_netconf.c ./notification-server.c
./mod_netconf.c:58:19: fatal error: unixd.h: No such file or directory
 #include <unixd.h>
                   ^
compilation terminated.
In file included from ./notification-server.c:34:0:
./notification_module.h:48:19: fatal error: httpd.h: No such file or directory
 #include <httpd.h>
                   ^
compilation terminated.
make[2]: *** [webgui-backend] Error 1
make[2]: Leaving directory `/var/www/netopeer-gui/install/mod_netconf/src'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/var/www/netopeer-gui/install/mod_netconf'
make: *** [install-recursive] Error 1

--------------------------------------------------------------------
I also make sure the apache server is installed and running well->
root@netconf:/etc/apache2/conf-available# service apache2 status
 * apache2 is running

How should I do for the next step?

**Comment by beyondjjw** [comment]
I met this problem on the ubuntu too.The same error was reported.I'm sure apache2 is working very well.

**Comment by alexadavid** [comment]
We have released new version (v2.0.0) of netopeergui using new UI and backend technologies (Libnetconf2 and netopeerguid instead of old mod_netconf). The installation script for centos7 could be found here https://github.com/CESNET/Netopeer-GUI/blob/master/install/centos7/install.sh
