### ISSUE TITLE
Apply All Changes won't Commit 

### ISSUE THREAD

**Issue by tbrito01** [CESNET/Netopeer-GUI#89]
Hi,

We are logged to our server via Netopeer GUI. Attempting to commit a change unsuccessfully. 

1. Candidate database is locked.
2. Edit a description of a parameter in the database.
3. Click on the Apply all changes button

We are able to edit the database but it won't commit it. Is there a commit button in the GUI? I could not find it. 
Is something else we need to do in order to see the commit button in the tool?

Thanks,

Tatiana

**Comment by alexadavid** [comment]
Hello, I'm a little bit busy right now, I'll go through all of your issues at the begin of next week

**Comment by tbrito01** [comment]
Ok thamks for the update.

**Comment by alexadavid** [comment]
There is no <commit> button in terms of netconf protocol. Button "apply all changes" creates <edit-config> request.

If your datastore is locked, you have to unlock it first - use the lock/unlock icon in top navigation bar in NetopeerGUI.

**Comment by sameeralirock** [comment]
Hi Alex,

But still after Apply changes the config is coming in candidate database but how to commit the config so that it is updated in running database? there is no commit button after Apply changes button.

TIA

**Comment by sameeralirock** [comment]
Hi Alex,

I am also facing the same issue, the config is getting into candidate database but to make it effective on the device it should be committed in running database but there is no such option in netopeer-GUI, please help us
TIA

**Comment by alexadavid** [comment]
you can use copy-config from candidate to running only. This version of netopeerGUI does not support <commit> action yet. The apply changes button creates just <edit-config> request. I'll discuss the posibilities how to implement <commit> action with mod_netconf development team.
