### ISSUE TITLE
Apply All Changes won't Commit

### ISSUE THREAD

**Issue by tbrito01** [CESNET/Netopeer-GUI#90]
Hi,

We are logged to our server via Netopeer GUI. Attempting to commit a change unsuccessfully. 

1. Candidate database is locked.
2. Edit a description of a parameter in the database.
3. Click on the Apply all changes button

We are able to edit the database but it won't commit it. Is there a commit button in the GUI? I could not find it. 
Is something else we need to do in order to see the commit button in the tool?

Thanks,

Tatiana

**Comment by alexadavid** [comment]
duplicate #89
