### ISSUE TITLE
Not compiling with recent libnetconf and libwebsockets

### ISSUE THREAD

**Issue by lpenz** [CESNET/Netopeer-GUI#91]
I tried to create a docker for netopeer-gui, but I was unable to compile it with the current libnetconf and libwebsockets. The results can be seen at:
https://travis-ci.org/lpenz/Netopeer-GUI/builds/111364445
The code itself is in the Dockerfile present at:
https://github.com/lpenz/Netopeer-GUI/tree/docker
Am I doing something wrong?

**Comment by alexadavid** [comment]
Hello, what version of centos are you using?

**Comment by cejkato2** [comment]
Hello, can you try to change https://github.com/lpenz/Netopeer-GUI/blob/docker/Dockerfile#L46 to
```
./configure --without-notifications
```
This will disable notifications and therefore avoid the issue with different api.

Other solution (that supports notifications) can be to clone specific older version of libwebsockets: https://github.com/cejkato2/libwebsockets
