### ISSUE TITLE
Netopeer-GUI installation problem

### ISSUE THREAD

**Issue by jurocks** [CESNET/Netopeer-GUI#95]
Hi,

I am having similar issues that in issue #92, but that issue was closed because solution should be in issue #93, but there the issue was with Ubuntu and I am running Centos 7. Here are the ./configure and make install outputs:

./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking for rpmbuild... rpmbuild
checking for httpd... yes
checking for apachectl... /usr/sbin/apachectl
checking for php... /usr/bin/php
checking for php module dom... yes
checking for php module json... yes
checking for php module xml... yes
checking for php module pdo... yes
checking for php module intl... yes
checking for php module sysvsem... yes
checking for pyang... yes
checking for python... /usr/bin/python
checking for rpmbuild... (cached) rpmbuild
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating netopeergui.conf
config.status: creating pyang/Makefile
=== configuring in mod_netconf (/var/www/netopeer-gui/install/mod_netconf)
configure: running /bin/sh ./configure --disable-option-checking '--prefix=/usr/local'  --cache-file=/dev/null --srcdir=.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for apxs2... no
checking for apxs... /usr/bin/apxs
checking for rpmbuild... rpmbuild
checking for httpd... yes
checking for apachectl... /usr/sbin/apachectl
checking for rpmbuild... (cached) rpmbuild
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for json... yes
checking for apr... yes
checking for aprutil... yes
checking for netconf... yes
checking for xml... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for websockets... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for int64_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for getdelim... yes
checking for gettimeofday... yes
checking for memset... yes
checking for socket... yes
checking for strdup... yes
checking for strerror... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: creating mod_netconf.spec
config.status: creating conf.d/Makefile
config.status: creating src/Makefile
config.status: executing depfiles commands

------------------------------------------------------------------------
mod_netconf 1.0.2
------------------------------------------------------------------------

Configuration Options Summary:

Documentation..........:

Compilation............: make (or gmake)
  asxs.................:
  LIBS.................: -ljson-c   -lnetconf   -lxml2   -lwebsockets
  CFLAGS...............: -I/usr/include/json-c     -I/usr/include/libxml2     -DWITH_NOTIFICATIONS

Installation...........: make install (as root if needed, with 'su' or 'sudo')
  prefix...............: /usr/local
  python module dir....:
  webgui dir...........:
  webgui name..........:
  httpdmoduledir.......: Apache default path
  httpdconfddir........: /etc/httpd/conf.d
Su user for process:...............:
Su group for process:..............:
Chown user for sock file:...............:
Chown group for sock file:..............:

------------------------------------------------------------------------
netopeergui 1.0.0
------------------------------------------------------------------------

Configuration Options Summary:

Documentation..........:

Compilation............: make (or gmake)
  asxs.................:
  LIBS.................:
  CFLAGS...............:

Components
  mod_netconf..........: yes
  pyang plugins........: yes

Installation...........: make install (as root if needed, with 'su' or 'sudo')
  prefix...............: /usr/local
  python module dir....: /usr/lib/python2.7/site-packages/pyang/plugins
  webgui dir...........: /var/www
  webgui name..........: netopeer-gui
  httpdmoduledir.......: Apache default path
  httpdconfddir........: /etc/httpd/conf.d

make install
Making install in mod_netconf
make[1]: Entering directory `/var/www/netopeer-gui/install/mod_netconf'
Making install in src
make[2]: Entering directory `/var/www/netopeer-gui/install/mod_netconf/src'
gcc -ljson-c   -lwebsockets   -lnetconf   -lxml2   -I/usr/include/json-c       -I/usr/include/libxml2   -DWITH_NOTIFICATIONS -DHTTP                                                                                                                                                                                               D_INDEPENDENT  `apr-1-config  --cflags --cppflags --includes --link-ld` -I/usr/include/httpd  -laprutil-1 -o webgui-backend ./mod_n                                                                                                                                                                                               etconf.c ./notification-server.c
./mod_netconf.c:162:63: error: unknown type name ‘LIBSSH2_SESSION’
 int netconf_callback_ssh_hostkey_check (const char* hostname, LIBSSH2_SESSION *session)
                                                               ^
./mod_netconf.c:183:3: error: unknown type name ‘LIBSSH2_USERAUTH_KBDINT_PROMPT’
   const LIBSSH2_USERAUTH_KBDINT_PROMPT* prompts,
   ^
./mod_netconf.c:184:3: error: unknown type name ‘LIBSSH2_USERAUTH_KBDINT_RESPONSE’
   LIBSSH2_USERAUTH_KBDINT_RESPONSE* responses,
   ^
./mod_netconf.c: In function ‘forked_proc’:
./mod_netconf.c:2332:42: error: ‘netconf_callback_ssh_hostkey_check’ undeclared (first use in this function)
  nc_callback_ssh_host_authenticity_check(netconf_callback_ssh_hostkey_check);
                                          ^
./mod_netconf.c:2332:42: note: each undeclared identifier is reported only once for each function it appears in
./mod_netconf.c:2333:34: error: ‘netconf_callback_sshauth_interactive’ undeclared (first use in this function)
  nc_callback_sshauth_interactive(netconf_callback_sshauth_interactive);
                                  ^
./notification-server.c:118:11: warning: ‘enum libwebsocket_callback_reasons’ declared inside parameter list [enabled by default]
           void *in, size_t len)
           ^
./notification-server.c:118:11: warning: its scope is only this definition or declaration, which is probably not what you want [ena                                                                                                                                                                                               bled by default]
./notification-server.c:118:11: warning: ‘struct libwebsocket’ declared inside parameter list [enabled by default]
./notification-server.c:117:38: error: parameter 3 (‘reason’) has incomplete type
   enum libwebsocket_callback_reasons reason, void *user,
                                      ^
./notification-server.c: In function ‘callback_http’:
./notification-server.c:233:3: warning: passing argument 1 of ‘lws_send_pipe_choked’ from incompatible pointer type [enabled by def                                                                                                                                                                                               ault]
   } while (!lws_send_pipe_choked(wsi));
   ^
In file included from ./notification-server.c:33:0:
/usr/local/include/libwebsockets.h:1953:1: note: expected ‘struct lws *’ but argument is of type ‘struct libwebsocket *’
 lws_send_pipe_choked(struct lws *wsi);
 ^
./notification-server.c:282:15: error: dereferencing pointer to incomplete type
   fd_lookup[pa->fd] = count_pollfds;
               ^
./notification-server.c:283:33: error: dereferencing pointer to incomplete type
   pollfds[count_pollfds].fd = pa->fd;
                                 ^
./notification-server.c:284:37: error: dereferencing pointer to incomplete type
   pollfds[count_pollfds].events = pa->events;
                                     ^
./notification-server.c:291:19: error: dereferencing pointer to incomplete type
   m = fd_lookup[pa->fd];
                   ^
./notification-server.c:298:23: error: dereferencing pointer to incomplete type
   pollfds[fd_lookup[pa->fd]].events = pa->events;
                       ^
./notification-server.c:298:41: error: dereferencing pointer to incomplete type
   pollfds[fd_lookup[pa->fd]].events = pa->events;
                                         ^
./notification-server.c: At top level:
./notification-server.c:607:4: warning: ‘enum libwebsocket_callback_reasons’ declared inside parameter list [enabled by default]
    void *user, void *in, size_t len)
    ^
./notification-server.c:607:4: warning: ‘struct libwebsocket’ declared inside parameter list [enabled by default]
./notification-server.c:606:39: error: parameter 3 (‘reason’) has incomplete type
    enum libwebsocket_callback_reasons reason,
                                       ^
./notification-server.c: In function ‘callback_notification’:
./notification-server.c:683:5: warning: passing argument 1 of ‘lws_send_pipe_choked’ from incompatible pointer type [enabled by def                                                                                                                                                                                               ault]
     if (lws_send_pipe_choked(wsi)) {
     ^
In file included from ./notification-server.c:33:0:
/usr/local/include/libwebsockets.h:1953:1: note: expected ‘struct lws *’ but argument is of type ‘struct libwebsocket *’
 lws_send_pipe_choked(struct lws *wsi);
 ^
./notification-server.c: At top level:
./notification-server.c:800:38: error: array type has incomplete element type
 static struct libwebsocket_protocols protocols[] = {
                                      ^
./notification-server.c: In function ‘notification_init’:
./notification-server.c:865:10: warning: assignment makes pointer from integer without a cast [enabled by default]
  context = libwebsocket_create_context(&info);
          ^
make[2]: *** [webgui-backend] Error 1
make[2]: Leaving directory `/var/www/netopeer-gui/install/mod_netconf/src'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/var/www/netopeer-gui/install/mod_netconf'
make: *** [install-recursive] Error 1

So I have no idea where to look for this problem. LIBSSH and Libwebsockets should be installed ok.

Thanks beforehand your help!

**Comment by alexadavid** [comment]
Ahoj tome,
gratuluji k úspěchu s prezentací na CNMS! 

Mohl bych tě poprosit, jeslti bys mohl zareagovat na tuto issue na githubu? Týká se opět instalace na ubuntu.

Díky :)
--
S přáním příjemného zbytku dne
David Alexa

tel:    773685283
web: www.davidalexa.cz

**Comment by cejkato2** [comment]
Tentokrát prý centos ;-)
Na to bychom měli mít vagrant, ale na novou verzi, že?
T.


Dne 29. dubna 2016 19:36:23 David Alexa <notifications@github.com> napsal:

> Ahoj tome,
> gratuluji k úspěchu s prezentací na CNMS!
>
> Mohl bych tě poprosit, jeslti bys mohl zareagovat na tuto issue na githubu? 
> Týká se opět instalace na ubuntu.
>
> Díky :)
> --
> S přáním příjemného zbytku dne
> David Alexa
>
> tel:    773685283
> web: www.davidalexa.cz
>
>
>

**Comment by cejkato2** [comment]
Jo a díky, jsem rád, že jsme cnms zvládli, a jsem vděčný, že kluci pomohli.
T.


Dne 29. dubna 2016 19:36:23 David Alexa <notifications@github.com> napsal:

> Ahoj tome,
> gratuluji k úspěchu s prezentací na CNMS!
>
> Mohl bych tě poprosit, jeslti bys mohl zareagovat na tuto issue na githubu? 
> Týká se opět instalace na ubuntu.
>
> Díky :)
> --
> S přáním příjemného zbytku dne
> David Alexa
>
> tel:    773685283
> web: www.davidalexa.cz
>
>
>

**Comment by cejkato2** [comment]
Hi,

please the following:
for libssh: https://github.com/CESNET/Netopeer-GUI/blob/netopeerguid/install/centos7/install.sh#L7

for libwebsockets: https://github.com/CESNET/Netopeer-GUI/blob/netopeerguid/install/centos7/install.sh#L30

**Comment by jurocks** [comment]
Hi, 

thanks for that! But I still run into problems. I tried to use those commands to my already "installed" netopeer-gui and then I removed it and installed all from the start as in the script. 

First problem was with:

git clone -b devel --depth 1 https://github.com/CESNET/libyang.git

git clone -b devel --depth 1 https://github.com/CESNET/libyang.git
Cloning into 'libyang'...
warning: Could not find remote branch devel to clone.
fatal: Remote branch devel not found in upstream origin

so I used just basic clone command:
git clone https://github.com/CESNET/libyang.git

Everything went ok until mod_netconf make command which again produces same kind of errors:

 make
Making all in src
make[1]: Entering directory `/var/www/mod_netconf/src'
gcc -Wall -Wextra -I/usr/include/json-c      -pthread   -DWITH_NOTIFICATIONS -O3 -o netopeerguid ./netopeerguid.c ./notification_server.c -ljson-c   -lnetconf2   -lyang    -lwebsockets
./notification_server.c:114:11: warning: ‘enum libwebsocket_callback_reasons’ declared inside parameter list [enabled by default]
           void *in, size_t UNUSED(len))
           ^
./notification_server.c:114:11: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
./notification_server.c:114:11: warning: ‘struct libwebsocket’ declared inside parameter list [enabled by default]
./notification_server.c:113:38: error: parameter 3 (‘reason’) has incomplete type
   enum libwebsocket_callback_reasons reason, void *user,
                                      ^
./notification_server.c: In function ‘callback_http’:
./notification_server.c:132:3: warning: implicit declaration of function ‘libwebsockets_serve_http_file’ [-Wimplicit-function-declaration]
   if (libwebsockets_serve_http_file(context, wsi, buf, whitelist[n].mimetype, NULL, 0))
   ^
./notification_server.c:165:4: warning: implicit declaration of function ‘libwebsocket_write’ [-Wimplicit-function-declaration]
    m = libwebsocket_write(wsi, buffer, n, LWS_WRITE_HTTP);
    ^
./notification_server.c:173:3: warning: passing argument 1 of ‘lws_send_pipe_choked’ from incompatible pointer type [enabled by default]
   } while (!lws_send_pipe_choked(wsi));
   ^
In file included from ./notification_server.c:33:0:
/usr/local/include/libwebsockets.h:1953:1: note: expected ‘struct lws *’ but argument is of type ‘struct libwebsocket *’
 lws_send_pipe_choked(struct lws *wsi);
 ^
./notification_server.c:174:3: warning: implicit declaration of function ‘libwebsocket_callback_on_writable’ [-Wimplicit-function-declaration]
   libwebsocket_callback_on_writable(context, wsi);
   ^
./notification_server.c:204:3: warning: implicit declaration of function ‘libwebsockets_get_peer_addresses’ [-Wimplicit-function-declaration]
   libwebsockets_get_peer_addresses(context, wsi, (int)(long)in, client_name,
   ^
./notification_server.c:222:15: error: dereferencing pointer to incomplete type
   fd_lookup[pa->fd] = count_pollfds;
               ^
./notification_server.c:223:33: error: dereferencing pointer to incomplete type
   pollfds[count_pollfds].fd = pa->fd;
                                 ^
./notification_server.c:224:37: error: dereferencing pointer to incomplete type
   pollfds[count_pollfds].events = pa->events;
                                     ^
./notification_server.c:231:19: error: dereferencing pointer to incomplete type
   m = fd_lookup[pa->fd];
                   ^
./notification_server.c:238:23: error: dereferencing pointer to incomplete type
   pollfds[fd_lookup[pa->fd]].events = pa->events;
                       ^
./notification_server.c:238:41: error: dereferencing pointer to incomplete type
   pollfds[fd_lookup[pa->fd]].events = pa->events;
                                         ^
./notification_server.c:113:38: warning: unused parameter ‘reason’ [-Wunused-parameter]
   enum libwebsocket_callback_reasons reason, void *user,
                                      ^
./notification_server.c: At top level:
./notification_server.c:515:4: warning: ‘enum libwebsocket_callback_reasons’ declared inside parameter list [enabled by default]
    void *user, void *in, size_t len)
    ^
./notification_server.c:515:4: warning: ‘struct libwebsocket’ declared inside parameter list [enabled by default]
./notification_server.c:514:39: error: parameter 3 (‘reason’) has incomplete type
    enum libwebsocket_callback_reasons reason,
                                       ^
./notification_server.c: In function ‘callback_notification’:
./notification_server.c:582:17: warning: passing argument 1 of ‘lws_send_pipe_choked’ from incompatible pointer type [enabled by default]
                 if (lws_send_pipe_choked(wsi)) {
                 ^
In file included from ./notification_server.c:33:0:
/usr/local/include/libwebsockets.h:1953:1: note: expected ‘struct lws *’ but argument is of type ‘struct libwebsocket *’
 lws_send_pipe_choked(struct lws *wsi);
 ^
./notification_server.c:514:39: warning: unused parameter ‘reason’ [-Wunused-parameter]
    enum libwebsocket_callback_reasons reason,
                                       ^
./notification_server.c: At top level:
./notification_server.c:704:38: error: array type has incomplete element type
 static struct libwebsocket_protocols protocols[] = {
                                      ^
./notification_server.c: In function ‘notification_init’:
./notification_server.c:777:2: warning: implicit declaration of function ‘libwebsocket_create_context’ [-Wimplicit-function-declaration]
  context = libwebsocket_create_context(&info);
  ^
./notification_server.c:777:10: warning: assignment makes pointer from integer without a cast [enabled by default]
  context = libwebsocket_create_context(&info);
          ^
./notification_server.c: In function ‘notification_close’:
./notification_server.c:792:3: warning: implicit declaration of function ‘libwebsocket_context_destroy’ [-Wimplicit-function-declaration]
   libwebsocket_context_destroy(context);
   ^
./notification_server.c: In function ‘notification_handle’:
./notification_server.c:820:3: warning: implicit declaration of function ‘libwebsocket_callback_on_writable_all_protocol’ [-Wimplicit-function-declaration]
   libwebsocket_callback_on_writable_all_protocol(&protocols[PROTOCOL_NOTIFICATION]);
   ^
./notification_server.c:843:5: warning: implicit declaration of function ‘libwebsocket_service_fd’ [-Wimplicit-function-declaration]
     if (libwebsocket_service_fd(context, &pollfds[n]) < 0) {
     ^
./notification_server.c: At top level:
./notification_server.c:704:38: warning: ‘protocols’ defined but not used [-Wunused-variable]
 static struct libwebsocket_protocols protocols[] = {
                                      ^
make[1]: *** [netopeerguid] Error 1
make[1]: Leaving directory `/var/www/mod_netconf/src'
make: *** [all-recursive] Error 1

So what should I try next?

**Comment by huzaifazafar108** [comment]
Hey, did you find a solution to this? I am facing most of the errors faced by you, can you help?

**Comment by alexadavid** [comment]
For mod_netconf issues, please the mod_netconf project https://github.com/CESNET/mod_netconf
Notice: We have released new version (v2.0.0) of netopeergui using new UI and backend technologies (Libnetconf2 and netopeerguid instead of old mod_netconf). The installation script for centos7 could be found here https://github.com/CESNET/Netopeer-GUI/blob/master/install/centos7/install.sh (as it was mentioned). But this script was already mentioned by cejkato2
