### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ustcpxy** [CESNET/Netopeer-GUI#97]
Hello,
I met an error when I install the Netopeer-GUI on Debian Testing. 

 $ ./configure                           
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking for rpmbuild... no
checking for httpd... no
checking for apachectl... /usr/sbin/apachectl
checking for php... /usr/bin/php
checking for php module dom... yes
checking for php module json... yes
checking for php module xml... yes
checking for php module pdo... yes
checking for php module intl... yes
checking for php module sysvsem... yes
checking for rpmbuild... (cached) no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating netopeergui.conf
=== configuring in netopeerguid (/home/derek/github/Netopeer-GUI/install/netopeerguid)
configure: running /bin/bash ./configure --disable-option-checking '--prefix=/usr/local'  --cache-file=/dev/null --srcdir=.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for rpmbuild... no
checking for rpmbuild... (cached) no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for json... yes
checking for netconf2... yes
checking for yang... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
configure: error: Certificate path must be set.
configure: error: ./configure failed for netopeerguid

**Comment by alexadavid** [comment]
Hello, the certificate is required for notifications. So you should set the path for certificate (due to commit https://github.com/CESNET/netopeerguid/commit/dd2c41d062974a9ce89fec801b1c1faab49cbc1b) or run configure with ```----without-notifications```

**Comment by ustcpxy** [comment]
Hi alexadavid, 
Thank you very much. 
when I run the configure with --without-notifications, everything goes well.
